env:
  browser: true
  es2021: true

extends:
  - 'plugin:react/recommended'
  - airbnb
  - prettier
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules: { no-param-reassign: 0, no-unused-vars: 1 }
